Server completed (step 6 deleting comments and limited number)
jamila-sabaz/step pull request #10
Opened 2020-12-21 14:56 UTC by jamila-sabaz

2020-12-22 06:00 UTC, lorikeet-s requested changes

2020-12-22 06:00 UTC, lorikeet-s commented on portfolio/src/main/webapp/index.html
> +  <body onload="loadComments(this.value)">
This is returning the value of the selected object at the time of load, it's not at all clear what the selected object is here, is there a reason to do it this way instead of just fetching the appropriate element by id inside the function?

2020-12-23 03:55 UTC, lorikeet-s requested changes
I think accidentally made some of the changes in the step 5 PR, once you've submitted that can you update this PR and I'll approve it.

2020-12-23 04:16 UTC, jamila-sabaz commented
> I think accidentally made some of the changes in the step 5 PR, once you've submitted that can you update this PR and I'll approve it.

Ok, so I merged step 5 to base and resolved all conflicts, now step 5 and step 6 should be identical because step 5 already had all 6 steps done.

2020-12-23 05:00 UTC, lorikeet-s requested changes
one bit of dead code then you're good to submit

2020-12-23 05:00 UTC, lorikeet-s commented on portfolio/src/main/webapp/script.js
> +// function getNumberOfComments(){
remove unused code.

2020-12-23 05:37 UTC, jamila-sabaz commented on portfolio/src/main/webapp/script.js
> +// function getNumberOfComments(){
removed

2020-12-23 06:05 UTC, lorikeet-s approved these changes

2020-12-29 01:53 UTC, merged